### ISSUE TITLE
Plejd entities stops group propagation

### ISSUE THREAD

**Issue by mattiasjonsson** [klali/ha-plejd#10]
Turning On/Off Plejd entities in groups does not work as expected. The propagation in the list/group stops at the first Plejd entity. Perhaps HA needs some sort of callback of task completion to be able to continue propagating trough the list/group?

**Comment by klali** [comment]
I've seen this/similar behaviour recently from other components. I suspect this might be issues with the component not being async, I might play around with that though not sure if it will result in any real findings.

**Comment by klali** [comment]
I've just merged a partial re-write that uses dbus directly instead of bluepy, this seems to be solved with that.
