### ISSUE TITLE
Problem get it working

### ISSUE THREAD

**Issue by errno111** [klali/ha-plejd#13]
I have been trying to get this working on a new installation of Hassbian.

I have made the installation like this:

First i extracted the cryptoKey (not my exact key: 5BDB62A12E1012C2B4A71CE3F3D77786 )  and outputAdresses (only gave me a list of number like: 11,16,17,18,19 and so on. no name on rooms, is that right? )
then:
* sudo apt-get install python3-pip libglib2.0-dev
* sudo pip3 install bluepy
* copied /usr/local/lib/python3.7/dist-packages/bluepy > /srv/homeassistant/lib/python3.7/site-packages/bluepy
* sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /srv/homeassistant/lib/python3.7/site-packages/bluepy/bluepy-helper
* created directory /home/homeassistant.homeassistant/custom_components
* downloaded the three files: __init__.py , light.py, manifest.json

added this at the end to configuration.yaml (i didn´t add all devices yet, just som to start)

light:
  - platform: plejd
    crypto_key: 5BDB62A12E1012C2B4A71CE3F3D77786
    devices:
      11:
        name: bedroom
      16:
        name: kitchen_1
      17:
        name: kitchen_2
      18:
        name: bathroom

i can now see the devices in HA, but when trying to turn something on i get this error in the HA web interface: Misslyckades med att anropa tjänsten light/turn_on. 'handles'
and this in the log:

2019-08-09 21:47:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py", line 303, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/plejd/light.py", line 106, in turn_on
    plejd_write(pi, pi["handles"]["data"], plejd_enc_dec(pi["key"], pi["address"], payload))
KeyError: 'handles'

Does anyone know what i could have made wrong?

If i run "sudo hcitool lescan"  I get a long list of devices Like: 
FA:12:D5:9D:CA:21 P mesh
FA:12:D5:9D:CA:21 (unknown)
41:ED:60:44:4D:92 (unknown)
C7:B0:31:7B:36:D0 P mesh
C7:B0:31:7B:36:D0 (unknown)
41:ED:60:44:4D:92 (unknown)
……...

**Comment by klali** [comment]
This sounds like the same thing as #11 I should probably add some error handling around where the handles are populated.

You shouldn't install bluepy into the system python, it has to be installed into the homeassistant python. Though with the latest code on master bluepy should be installed automatically. Can you enable debug for the plejd component and post what you get before that error?

something like this to get debug from plejd:
```
logger:
  logs:
    custom_components.plejd: debug
```

edit: this will happen if the connection fails to establish but the devices are registered. We should probably not try to operate when there is no connection.
