### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by keylogicjohan** [klali/ha-plejd#2]
My setup is a raspberry pi 3+ with hassbian
I have run through the steps with pygatt and extrakting the crypto key, no problems here.

When i try to run it I can´t find any lights, no erreors in "home-assistant.log".
The only place where I can find a error is in "Configuration validation", when I check my config I get "Platform not found: light.plejd"

My guess is that something is initiating correctly.
Is there any sepererat logfiles for the plejd component?

/Johan

**Comment by klali** [comment]
On what version of homeassistant?

Did you put the light.py and __init__.py in a custom_components/plejd/ directory?

There's no separate logfile for the component, as homeassistant loads there should be something like this in your log though:
```
2019-05-26 20:52:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plejd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-05-26 20:52:38 INFO (MainThread) [homeassistant.loader] Loaded plejd from custom_components.plejd
```

**Comment by keylogicjohan** [comment]
I´m using version 0.94.4

Yes the files are in the right place I think, and my log file only containes the first row that you have in you´re log file.

![image](https://user-images.githubusercontent.com/19464881/60429766-17827400-9bfc-11e9-916f-3efa16a25779.png)

**Comment by klali** [comment]
I just updated my installation to 0.95.4, still runs fine.

I have my logging component at info, see the docs for that component for how to fine-tune it.
```
logger:
  default: info
```
 both the plejd component and pygatt itself logs a bit at info, there's a few setup messages from the component and as pygatt starts it prints something like:
```
2019-07-01 19:30:32 INFO (Thread-66) [pygatt.backends.gatttool.gatttool] Running...
2019-07-01 19:30:32 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Starting BLE scan
2019-07-01 19:30:38 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Discovered XX:XX:XX:XX:XX:XX (P mesh)
2019-07-01 19:30:38 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Discovered XX:XX:XX:XX:XX:XX (P mesh)
2019-07-01 19:30:38 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Discovered XX:XX:XX:XX:XX:XX (P mesh)
2019-07-01 19:30:38 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Discovered XX:XX:XX:XX:XX:XX (P mesh)
2019-07-01 19:30:38 INFO (Thread-5) [pygatt.backends.gatttool.gatttool] Discovered XX:XX:XX:XX:XX:XX (None)
```

The "P mesh" entries are plejd devices discovered.

**Comment by keylogicjohan** [comment]
I found out something else, I´m not running as 3B+ just a 3B..
Maybe this is the issue for me, sorry..

I´ve found something when I started logging som more 

> 2019-07-02 11:00:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plejd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-07-02 11:01:01 INFO (MainThread) [homeassistant.setup] Setting up plejd
2019-07-02 11:01:01 ERROR (MainThread) [homeassistant.setup] Setup failed for plejd: No setup function defined.

When I look at other custom components that I have on ny other HA installation, every one has a:

> def setup_platform(hass, config, add_entities, discovery_info=None):

I´m no good at python programming, is it needed or why to I get that error code?

I can run hcitool as a bash command and scan f
"hcitool lescan"
there i can find my "P mesh" devices
I can even use gatttool to connect to my "PAX Calima". 
I tried to connect to one of the "P mesh" devices but couldent get at connection, I guess i med the crypto key as well to get a connection.
So I think by bluetooth is up and running as it should

**Comment by klali** [comment]
If hcitool can scan for the devices it should be possible to get it running, not a problem of your hardware then.

The "No setup function defined" error looks interesting, I don't get that, will have to see if I can provoke it.

The `setup_platform` function is in light.py and should be the one called since it's the component being used. Quite a few of the components included with home assistant has an empty __init__.py and a `setup_platform` in the component file like this.

**Comment by keylogicjohan** [comment]
After som vacation I started again..
Reinstalled it all over again, and it works, not shure what I missed the first time.

I can switch on/off the lights and dim them perfectly, but most of the time I don´t get the state of the plejd back.
Any idea why this is not working?

**Comment by klali** [comment]
Glad you got it (mostly) working.

I guess this is with the master branch, would you feel like trying the bluepy branch and see how that behaves in regards to getting states. It'd also be nice if you run the component in debug with something like:

```
logger:
  logs:
    custom_components.plejd: debug
```

**Comment by keylogicjohan** [comment]
Yes this is the master branch
It looks like the "light" component is loooking for device "1"

Attached my log file here, my plejd devices are 12,13,17,18
[home-assistant.log](https://github.com/klali/ha-plejd/files/3430452/home-assistant.log)

Will try to runt the hassio installation but it will have to wait a couple of weeks

**Comment by keylogicjohan** [comment]
I think I found it!

I started looking att the plejds id:s..
I opened the plejd app and looked under:
setting->handle units->clicked on one->about unit

there I got another mesh index then the ones I got from the backup.ab
When I switched to this mesh index my units work perfectly! even the readback

**Comment by keylogicjohan** [comment]
If you look in the backup.ab
Instead of "inputAddresses" I used "outputAdresses" 
That did the trick for me

**Comment by klali** [comment]
Interesting (and good find)!

Mine has the same values for the inputs and outputs, but if you have a more advanced setup I guess they might differ. It makes much more sense to use the outputs than inputs. Do you want to submit a pull request fixing the documentation?

**Comment by keylogicjohan** [comment]
I saw that you already fixed the docs, now it´s time to try it on hassio and a "thinkerboard s"
