### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by spripe** [klali/ha-plejd#23]
Hi,
In the "Plejd mobile application" I got brightness value directly. It show i.e 53%.

Everything works great in HA for me, but the brightness attribute is not set if not I turn_on/turn_off/change brightness first in i.e HA or in "Plejd mobile application". 

So, if I use an automation to load current brightness value and change that with 10%, then it cant load the current value. and the automation needs to jump and assume the current brightness value it will change from.

Is it possible to change this so the brightness value is loaded from the device directly and when state changes?

**Comment by klali** [comment]
Generally this should be updated when the brightness changes, no matter the source.

If you turn on debug logging for the component you'll be able to see what information it receives from the plejd network as the state changes. It'd be helpful if you could show what that log looks like and what you expect it to show.

**Comment by klali** [comment]
Please update this with more logs if this is still an issue.
