### ISSUE TITLE
Extracting crypto keys, small typo

### ISSUE THREAD

**Issue by prebbz** [klali/ha-plejd#33]
Really great initiative on ha-plejd, thanks so much for taking the time to contribute.
Your "how-to" guide on extracting the crypto keys is more or less accurate, except for the output Addresses which seems to be: 

`cat site.json  | jq '.PlejdMesh._outputAddresses'`

**Comment by klali** [comment]
They seem to have changed it, I'll update.

**Comment by prebbz** [comment]
Note, this was on iOS. I haven't verified android in any way.

**Comment by klali** [comment]
and I tried on android, so they've changed it a little bit (and fixed a typo).
