### ISSUE TITLE
Cannot use/login to Plejd integration since a few weeks ago

### ISSUE THREAD

**Issue by sundancekid80** [klali/ha-plejd#39]
Hi! I had had problems using the Plejd integration for a few weeks. When checking the log it seems as the commands propagated from i e google home are propagated into HA but nothing happens with the lights. When trying the same things through the Plejd app, nothing gets detected. 

Now, when trying to uninstall/reinstall the integration I get the following error:

2021-01-22 08:04:38Z ERR plejd-api Server returned status 400. probably invalid credentials, please verify.
(node:4096) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 400

I only copied the configuration so it shouldn't be a problem. Any tips for me regarding my problem(s)?

**Comment by klali** [comment]
I don't think you're running ha-plejd, there is no contact with the plejd http api in this integration.

At a guess you're running https://github.com/icanos/hassio-plejd
