### ISSUE TITLE
New test on Hass.io

### ISSUE THREAD

**Issue by BertilJ** [klali/ha-plejd#4]
This is really great work and we are many (Swedes) at least that is really looking forward to this.

I've just tested the new branch on Hass.io and I'm getting an error message that doesn't seem directly related to BLE.

> Invalid config for [light.plejd]: [device] is an invalid option for [light.plejd]. Check: light.plejd->device. (See ?, line ?). Please check the docs at https://home-assistant.io/components/light.plejd/

My config is this:

>   - platform: plejd
>     crypto_key: "XXXXXX"
>     device:
>       12:
>         name: Not known
>       13: 
>         name: Not known
>       16:
>         name: Not known
>       17:
>         name: Not known
>       20:
>         name: Not known

I'm running latest (0.96.3) Hass.io on a NUC.

Addition: Removing the config under light: is removing the error message, so could this be related to how it's configured?

**Comment by BertilJ** [comment]
I've looked a little more in to this and it seems that Python 3.7.3 doesn't work together with bluepy, MiFlora also stopped working after last upgrade.

Trying to manually install bluepy creates error messages as well on Hass.io propably due to Python 3.7.3.

**Comment by klali** [comment]
That specific error is due to a config error, it should be "devices", not "device" (the example in the README was wrong). Though bluepy not working on pythong 3.7(.3?) seems worrisome, I'm unsure what the proper python BLE library to use is.

**Comment by klali** [comment]
I'll close this in favor of #1 since they both deal with hass.io compatibility.
