### ISSUE TITLE
Unique entity id for lights

### ISSUE THREAD

**Issue by mist0706** [klali/ha-plejd#40]
Currently the lights are not assigned unique entity id's. This means that they cannot be assigned to a room in HASS

![image](https://user-images.githubusercontent.com/10143260/106112885-14d85f80-614e-11eb-8886-cfd0606efc8e.png)

The instructions specify using the Customizations menu to edit the entity however AREA/ROOM is not an customizeable option.

**Comment by klali** [comment]
I just pushed some code to https://github.com/klali/ha-plejd/tree/unique_id see if it solves your issue.

**Comment by mist0706** [comment]
That branch works perfectly!

![image](https://user-images.githubusercontent.com/10143260/106146595-241fd300-6177-11eb-94e8-6eb67bf1fd6f.png)
