### ISSUE TITLE
Shelly as BT-adapter?

### ISSUE THREAD

**Issue by anha7196** [klali/ha-plejd#61]
Hi!
I wanted to ask about the new Bluetooth capabilities of Home Assistant, where it is possible to use for example a shelly device as a remote Bluetooth adapter. Is this something that could be used for this plugin? It would be a great  and cheap way to get close to the plejd devices. 

https://www.home-assistant.io/blog/2022/12/07/release-202212/#bluetooth-proxy-using-shelly-devices

Thanks!

**Comment by klali** [comment]
not with this plugin, possibly with https://github.com/thomasloven/hass_plejd/

**Comment by anha7196** [comment]
Thanks for the answer!
