### ISSUE TITLE
Crypto key for iOS?

### ISSUE THREAD

**Issue by iCarl** [klali/ha-plejd#7]
Is rhere a known way to extract a crypto key for iOS?

**Comment by iCarl** [comment]
I think I managed to extract it by download a local backup of my iPhone.
The cryptokey cointains of segments of two characters followed by a dash.
Should the dashes be ignored in the configuration.yaml?
I also seem to have two separate cryptokeys, is this normal?

**Comment by iCarl** [comment]
I managed to get it to work!

**Comment by klali** [comment]
Can you provide instructions for others using ios devices? Did you manage to recover a site json file as well or was it stored in a different format?

**Comment by iCarl** [comment]
I opened a iPhone backup using iBackup Viewer.
Selected raw files, look for AppDomainGroup-group.com.plejd.consumer.light.
AppDomainGroup-group.com.plejd.consumer.light/Documents there should be two folders,
The folder that isn't named ".config" contains a .site-file with the crypto key.
