### ISSUE TITLE
DIM-02 with dual outputs

### ISSUE THREAD

**Issue by iCarl** [klali/ha-plejd#8]
I have a couple of DIM-02, but only one of the output channels can be controlled and found.
How do I control both outputs?

**Comment by BertilJ** [comment]
I've got several DIM-02 and I'm controlling both outputs. They just appear as separate lights once configured.

If you are using the app to find the channels, try the number above or below of the number you see in the app to get the right channel.

**Comment by iCarl** [comment]
I’ll try!

**Comment by klali** [comment]
This should just work. The .site json file should list all output adresses and thus have two for a dim-02.
